services:
  db:
    image: bitnami/postgresql:16.2.0
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: person
      POSTGRESQL_TIMEZONE: "UTC"
    ports:
      - 5432:5432