@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor individual as ind
participant keycloak as kk
participant person_service as prn
participant user_service as usr
participant individual_service as inds
database PersonDB as db

ind -> kk: registration request to \n api/v1/auth/register/individuals \n registration dto
kk -> kk: register individual keycloak realm
kk -> prn : register individual request to \n api/v1/persons/individuals/create \n IndividualRegistrationDto
prn -> prn : extract IndividualRegistrationDto \n to userDto and IndividualDto
prn -> usr : create user \n userDto
usr -> db : save user
prn -> inds : create individual \n individualDto
inds -> db : save individualEntity
prn -> ind : registration completed
@enduml