spring:
  application:
    name: users-manager
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/
    username: postgres
    password: password
    name: person
  flyway:
    user: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/person
    locations: classpath:db/migration
  mvc:
    log-request-details: true
server:
  port: 8088
logging:
  level:
    web: debug
    root: debug
